[package]
name = "envoy-tonic"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1"
prost = "0.11"
pbjson = "0.5"
pbjson-types = "0.5"
serde = "1.0"
tonic = { version = "0.8", features = ["gzip"] }
