[package]
name = "envoy-prost-tonic"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1"
prost = "0.11"
pbjson = "0.5"
pbjson-types = "0.5"
serde = { version = "1.0", features = ["derive"] }
tonic = { version = "0.8", features = ["gzip"] }
